services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP gRPC
    networks: [apm-net]

  wiremock:
    image: wiremock/wiremock:3.8.0
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: [ "--verbose" ]
    networks: [apm-net]

networks:
  apm-net:
    driver: bridge
