server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:demo;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true

observability:
  apm:
    vendor: otel
    applicationName: "wallet-platform"
    serviceName: "wallet-transfers"
    serviceVersion: "1.0.0"
    environment: "local"
    endpoint: "http://localhost:4317"
